### PR TITLE
updated the returned values for vcfFields()

### PR DESCRIPTION
**Pull request by Liubuntu**
Hi Val, 

I have modified the returned value for `vcfFields()$fixed`, which now returns "REF", "ALT", "QUAL", and "FILTER" instead of only specific field, by the original definition: 

```
!> selectMethod("fixed", "VCFHeader")
 Method Definition:

 function (x)
 {
     fixed <- c("QUAL", "FILTER", "ALT", "REF")
     lst <- slot(x, "header")
     lst[names(lst) %in% fixed]
 }
 <environment: namespace:VariantAnnotation>

 Signatures:
         x
 target  "VCFHeader"
 defined "VCFHeader"
```

In this way, it's more consistent with the output for `fixed(VCF object)`. 
```
> VCF <- scanVcf(fl)
> fixed(VCF)
DataFrame with 10376 rows and 4 columns
                 REF                ALT      QUAL      FILTER
      <DNAStringSet> <DNAStringSetList> <numeric> <character>
1                  A                  G       100        PASS
2                  C                  T       100        PASS
3                  G                  A       100        PASS
4                  C                  T       100        PASS
5                  C                  T       100        PASS
...              ...                ...       ...         ...
10372              A                  G       100        PASS
10373              A                  G       100        PASS
10374              A                  G       100        PASS
10375              G                  A       100        PASS
10376              G                  C       100        PASS
```
Also, in the package of `VCFArray`, we want to include as many columns as possible from the VCF file that could be converted into `VCFArray` object. with the new returned values for `vcfFields(...)`, the "REF", "QUAL", and "FILTER" columns are all able to be converted into `VCFArray` object. 
```
> fl <- system.file("extdata", "chr22.vcf.gz", package="VariantAnnotation")
> hdr <- scanVcfHeader(fl)
> fixed(hdr)
DataFrameList of length 1
names(1): ALT
> vcfFields(hdr)$fixed
[1] "REF"    "ALT"    "QUAL"   "FILTER"
```

Let me know for any questions or suggestions. Thanks!

Best,
Qian

### CODE REVIEW

**Comment by Liubuntu** [comment]
Hi @mtmorgan , 

I didn't make commits directly to VariantAnnotation, instead I forked this fold to my account and made a pull request. 

Qian

**Comment by vobencha** [comment]
@Liubuntu @mtmorgan This is confusing. I merged the pull request but `git log` shows @Liubuntu already committed this change on Oct 15?
```
commit 26713c74a90f5fde959f1de2783ac3bd28ceda09 (HEAD -> master, origin/master, origin/HEAD)
Merge: b4be665 64bca43
Author: vobencha <valerie.obenchain@roswellpark.org>
Date:   Wed Oct 17 05:32:15 2018 -0700

    Merge pull request #13 from Liubuntu/master
    
    updated the returned values for vcfFields()

commit 64bca43bd3ef5f76c0e36c34691a151c368f79de
Author: Qian Liu <qliu7@buffalo.edu>
Date:   Mon Oct 15 10:48:16 2018 -0400

    updated the returned values for vcfFields()
```

**Comment by vobencha** [comment]
Never mind, my fault. I didn't remember this 'double' pattern in a merge log.

**Comment by Liubuntu** [comment]
Thanks @vobencha for the merge!

**Pull request merged**
