### PR TITLE
Added vcfFields,VcfFile-method.

### PR DESCRIPTION
**Pull request by Liubuntu**
Hi @vobencha , 

I have just added the `vcfFields` generic and method for `character` and `VcfFile` objects. Please take a look. Thanks!

Best,
Qian

### CODE REVIEW

**Comment by vobencha** [comment]
Hi @Liubuntu 

- Add a man page with example.
- Add a unit test.
- Does this line really test what you want? For example, no error is thrown in this case:
```
> x = ''
> stopifnot(!is.na(x), length(x) > 0)
```
- That same line doesn't throw and informative error message when the second condition fails:
```
> x = character(0)
> stopifnot(!is.na(x), length(x) > 0)
Error: length(x) > 0 is not TRUE
```
How about
```
> x = "/path/to/file"
> stopifnot(!is.na(x), file.exists(x) > 0)
Error: file.exists(x) > 0 is not TRUE
```
- I think the main purpose of the function is to expose fields for subsetting which will ultimately be given to a ScanVcfParam object. If this is the case, I think we should also support a list of 'samples'.
```
Slots of the ScanVcfParam

> showClass("ScanVcfParam")
Class "ScanVcfParam" [package "VariantAnnotation"]

Slots:                                                                    
Name:              which             fixed              info              geno
Class: IntegerRangesList         character         character         character
                                         
Name:            samples         trimEmpty
Class:         character           logical

Extends: "ScanBVcfParam"
```
Thanks.
Val

**Comment by vobencha** [comment]
I agree with adding a `vcfFields,VCF` method. Doing this IMO makes an even stronger case for returning "samples". The VCF specs (https://samtools.github.io/hts-specs/VCFv4.2.pdf) refer to all of INFO, GENO, FIXED, ALT, as well as source, version etc as "fields". If the function is returning the fields in a file on disk or VCF object in R then I think it should probably return all fields in the header. I view this as a higher-level more user-friendly function than `scanVcfHeader`.

To me it doesn't make sense to tailor this function to `VCFArray` methods but have it live in `VariantAnnotation`. If you'd rather only return fields needed for `VCFArray` subsetting I think that should be a different function with a name specific to `VCFArray` and should not go in `VariantAnnotation`. I'm completely fine with that by the way.

**Comment by Liubuntu** [comment]
Hi Val, 

I have just edited the previous comment, and removed the `vcfFields,VCFArray` method. In constructing of `VCFArray`, we use `VCFArray(file, name = "")`, the purpose of implementing `vcfFields` method is to return the available entries for the `name` argument. 

Yes, now I found that to be a little bit too VCFArray-customized. And the `vcfFields` method name is more generic, I agree that including samples would make more sense and more consistent with the use of `scanvcfHeader` as a higher-level function. 

For the `VCFArray`, I favor not to add any specific function to only return the available values for `name` argument. I can add in the vignette and point users to the `vcfFields()` function, and consult the `geno/info/fixed` elements for available names. 

Best,
Qian

**Comment by vobencha** [comment]
Thanks @Liubuntu . Looks good. I think having a `vcfFields,VCFHeader-method` makes sense as a base method. Nice job. Thanks also for cleaning up the `VcfFile-class` man page.
Val

**Comment by Liubuntu** [comment]
Thanks @vobencha for merging it.

**Pull request merged**
