### PR TITLE
moved vcfFields() from 'SimpleList()' into 'CharacterList()'

### PR DESCRIPTION
**Pull request by Liubuntu**
Hi @vobencha , 

This new pull request has changed the returned value from `vcfFields()` into a `SimpleCharacterList`. Please take a look. Thanks!

Best,
Qian

### CODE REVIEW

**Comment by vobencha** [comment]
I didn't realize the default behavior of CharacterList() was to create a CompressedCharacterList (not SimpleCharacterList). I don't have a preference, I was just trying to go with what I thought the default would be.

I'm fine with the CompressedCharacterList and think we should leave the door open for the other derivative, SimpleCharacterList. In the interest of being as generic as possible, please change these things:
- the constructor should not specify compress=False
- the man pages should reference \link[IRanges]{CharacterList}, not Simple or Compressed
- the unit test should test for CharacterList, not Simple or Compressed

Thanks.

**Comment by Liubuntu** [comment]
Hi @vobencha , 

Now everything is in generic `CharacterList()`, with the default `compress=TRUE`. The link of `IRanges` is also added into the documentation. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
Thanks Val! The pull request for `GenomicFiles` is also ready. It depends on the `VariantAnnotation 1.27.6` now, and has the `\link[IRanges]{CharacterList}` in the documentation also. Can you take a quick look at this one also? Thanks! https://github.com/Bioconductor/GenomicFiles/pull/1/commits/a03971eb89c9deafccc20786bed386df8af2aa25

**Comment by mtmorgan** [comment]
I'll look at GenomicFiles.

**Pull request merged**
